# Generated by Django 6.0.4 on 2026-04-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=20)),
                ('duration_of_cooking', models.DurationField()),
            ],
        ),
    ]
