# Generated by Django 6.0.4 on 2026-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_restaurant_remove_menu_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='duration_of_cooking',
        ),
        migrations.AddField(
            model_name='dish',
            name='cook_time',
            field=models.IntegerField(default=0, help_text='Время готовки в минутах'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dish_images'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='currency',
            field=models.CharField(default='KZT'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
