# Generated by Django 6.0.4 on 2026-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='Без названия', max_length=100),
        ),
    ]
