# Generated by Django 6.0.4 on 2026-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='seasons',
        ),
        migrations.AddField(
            model_name='menu',
            name='season',
            field=models.CharField(choices=[('winter', 'Зимнее'), ('spring', 'Весеннее'), ('summer', 'Летнее'), ('autumn', 'Осеннее')], default='summer', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(related_name='menus', to='menu.dish'),
        ),
    ]
